;; -*- lexical-binding: t; -*-

(require 'use-package)

(defun meow-setup ()
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
  (meow-motion-define-key
   '("k" . meow-next)
   '("l" . meow-prev)
   '("<escape>" . ignore))
  (meow-leader-define-key
   ;; Use SPC (0-9) for digit arguments.
   '("1" . meow-digit-argument)
   '("2" . meow-digit-argument)
   '("3" . meow-digit-argument)
   '("4" . meow-digit-argument)
   '("5" . meow-digit-argument)
   '("6" . meow-digit-argument)
   '("7" . meow-digit-argument)
   '("8" . meow-digit-argument)
   '("9" . meow-digit-argument)
   '("0" . meow-digit-argument)
   '("SPC" . set-mark-command)
   '("/" . meow-keypad-describe-key)
   '("?" . meow-cheatsheet))
  (meow-normal-define-key
   '("0" . meow-expand-0)
   '("9" . meow-expand-9)
   '("8" . meow-expand-8)
   '("7" . meow-expand-7)
   '("6" . meow-expand-6)
   '("5" . meow-expand-5)
   '("4" . meow-expand-4)
   '("3" . meow-expand-3)
   '("2" . meow-expand-2)
   '("1" . meow-expand-1)
   '("-" . negative-argument)
   '("h" . meow-reverse)
   '("H" . avy-goto-char-timer)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("[" . meow-beginning-of-thing)
   '("]" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("c" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-next-word)
   '("E" . meow-next-symbol)
   '("f" . meow-find)
   '("F" . meow-find-expand)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("j" . meow-left)
   '("J" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("k" . meow-next)
   '("K" . meow-next-expand)
   '("l" . meow-prev)
   '("L" . meow-prev-expand)
   '(";" . meow-right)
   '(":" . meow-right-expand)
   '("m" . meow-join)
   '("n" . meow-search)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("p" . meow-yank)
   '("P" . meow-yank-pop)
   '("q" . meow-quit)
   '("Q" . meow-goto-line)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-kill)
   '("t" . meow-till)
   '("T" . meow-till-expand)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("w" . meow-mark-word)
   '("W" . meow-mark-symbol)
   '("x" . meow-line)
   '("X" . meow-line-expand)
   '("y" . meow-save)
   '("Y" . meow-sync-grab)
   '("z" . meow-pop-selection)
   '("'" . repeat)
   '("=" . indent-region)
   '("(" . backward-sexp)
   '(")" . forward-sexp)
   '("{" . backward-paragraph)
   '("}" . forward-paragraph)
   '("<escape>" . ignore)))

(use-package key-chord
  :ensure t
  :config (progn (setq key-chord-two-keys-delay 0.05) ;default is 0.1 seconds, we use 0.05 seconds.
                 (key-chord-mode 1)))

(use-package meow
  :ensure t
  :config (progn (meow-setup)
                 (meow-global-mode)
                 (key-chord-define meow-insert-state-keymap "fd" #'meow-insert-exit)
                 (add-to-list 'meow-char-thing-table '(?u . url))
                 (add-to-list 'meow-char-thing-table '(?\s . whitespace))
                 ;; disable meow in all magit buffers (otherwise
                 ;; navigation commands override log and drop on k and
                 ;; l)
                 (add-hook 'Buffer-menu-mode-hook (lambda () (meow-mode -1)))
                 (add-hook 'magit-mode-hook (lambda () (meow-mode -1)))))

(use-package meow-tree-sitter
  :ensure t
  :config (meow-tree-sitter-register-defaults))

(provide 'modal-editing)
